apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook
  labels:
    app: admission-webhook
webhooks:
  - name: dast.security.banzaicloud.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: "/ingress"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lKQVBkMCtLaE04NW5STUEwR0NTcUdTSWIzRFFFQkN3VUFNRTR4Q3pBSkJnTlYKQkFZVEFsVlRNUzh3TFFZRFZRUUREQ1pyWVdacllTMW9aV0ZrYkdWemN5NXJZV1pyWVM1emRtTXVZMngxYzNSbApjaTVzYjJOaGJERU9NQXdHQTFVRUNnd0ZhMkZtYTJFd0hoY05NVGt3TnpFMk1UUXlNREl5V2hjTk1Ua3dPREUxCk1UUXlNREl5V2pCT01Rc3dDUVlEVlFRR0V3SlZVekV2TUMwR0ExVUVBd3dtYTJGbWEyRXRhR1ZoWkd4bGMzTXUKYTJGbWEyRXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3hEakFNQmdOVkJBb01CV3RoWm10aE1JSUJJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZPN2hmTTk0SDNtK0g1WTZ0N1hoek5mc0wrOFkycjQyCk9Sd2dpa09zY2JkaFBHM3oxVVhaWmFnOU1wTFFYVGhXMklrUmloVllRd0xkSlZSb3YzTks3dVV3U3VuNldiVXkKWGxhM1NiMkx4ZVlyaGNqK0hiNVpoYmwvSXpLRDZiNGdxTzJVVjI0dm9EclQ5S2pkWlBDcHp5alhDb3FEKzJrTQpha3R5azB3azAySGpVU1J6M0VOZlFCY252NVZ4MCtiZ0xHem5qd2xjYmFXZnY5Ly94dVllZDNkckNJYlRFaDJXClVXblMxVG1UTjM5YzFKWEN5aGdOeUhyVlVqNXh4OElYakVQQWlMN1VMc2loS3FmeU13K25QMUxBbURsWEtweVEKaXlhVUh0RzJtZUg5RTdFM2JxWnFSblp6SGMweVVJL0xxM1lHbFJTUnN3NlhtTE56NDl2RFp3SURBUUFCb3p3dwpPakFNQmdOVkhSTUVCVEFEQVFIL01Bc0dBMVVkRHdRRUF3SUJCakFkQmdOVkhRNEVGZ1FVcnY5UndhaEdyN055Ck9Pd21VVVpBOFcrTW43c3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS2NzS2xONE5zZ1BkVVNmZVZnempac00KY2VqZE9sbVplR0Nncy9CejlrZ0hwcE1xeEt3Vm80a2FyRkpMZ2VHWjk0R1l4MFdVSHpnWHdKL1Zoc0tVb3Q3MQpXRGdIR1hvYkNUZFFsUWVzZ1kvNzN5anlMYXBvSUFKejVFWGJYOTN3ZExCZ2pscThvUG9vVHArQk03Q1NMZS9ZClNkc0ZLandxV2J4SkN3Y2lqZXArU3NZMytTTGRDcXRuVVBiSU54amtQWk5IQmFZSGk1SkpyN1AzTnhJSXBQZTgKRHpZZTFXK2xlWnNFdnpuSkdKa3duN0U0ZHVVSHZLYVdSNXRnL0swWllpNGFFOG94b1c2dG1XWmVLUmhxV0RkRApSYndMMTk0SGxlZ1hCRy9vdjhrd2dwT0VhbHhmaDgxY0NLd2YvWkJ3WFRJa2ZTV3ZUY29EZndCa0pWL1BaZmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["extensions"]
        apiVersions: ["v1beta1"]
        resources: ["ingresses"]
