
apiVersion: v1
kind: Service
metadata:
  name: dast-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    control-plane: dast-operator
    controller-tools.k8s.io: "1.0"
