apiVersion: v1
kind: Namespace
metadata:
  name: zapproxy
---
apiVersion: security.banzaicloud.io/v1alpha1
kind: Dast
metadata:
  name: dast-sample-external
  namespace: zapproxy
spec:
  zapproxy:
    name: dast-test-external
    apikey: abcd1234
  analyzer:
    image: banzaicloud/dast-analyzer:latest
    name: external-test
    target: https://example.com
