apiVersion: security.banzaicloud.io/v1alpha1
kind: Dast
metadata:
  name: dast-sample
spec:
  zaproxy:
    name: dast-test
    apikey: abcd1234
    config:
      - "replacer.full_list(0).description=auth1"
      - "replacer.full_list(0).enabled=true"
      - "replacer.full_list(0).matchtype=REQ_HEADER"
      - "replacer.full_list(0).matchstr=Authorization"
      - "replacer.full_list(0).regex=false"
      - "replacer.full_list(0).replacement=123456789"
      - "replacer.full_list(1).description=auth2"
      - "replacer.full_list(1).enabled=true"
      - "replacer.full_list(1).matchtype=REQ_HEADER"
      - "replacer.full_list(1).matchstr=AnotherHeader"
      - "replacer.full_list(1).regex=false"
      - "replacer.full_list(1).replacement=abcdefghi"